info:
  app.name: "@project.name@"
  app.description: "@project.description@"
  app.version: "@project.version@"
  build.artifact: "@project.artifactId@"
  build.time: "@build.timestamp@"

app:
  url: http://localhost:8080
  rememberme-cookie-key: starter
  rememberme-cookie-valid-in-days: 31
  default-email-sender: no-reply@starter.com
  login-lock-attempts: 10
  login-lock-minutes: 30

mongodb:
  uri: mongodb://localhost/starter6?w=1&wtimeoutMS=0&journal=true
  database: starter6

spring:
  jackson:
    serialization:
      write-date-timestamps-as-nanoseconds: false
  
  resources:
    cache:
      period: 31556926
 
  mail:
    host: localhost    

  async:
    core-pool-size: 2
    max-pool-size: 20
    queue-capacity: 200
    thread-name-prefix: starter-async-executor

  main:
    banner-mode: log 


server:
  port: 80
  servlet:
    session:
      timeout: 480
  compression:
     enabled: true
     mime-types: text/html,text/xml,text/plain,text/css,application/json,application/javascript,image/svg+xml,application/x-font-ttf,application/x-font-truetype,application/x-font-opentype,application/vnd.ms-fontobject,application/font-sfnt     
  forward-headers-strategy: framework

logging:
  level:
    org.springframework: WARN
    org.mongodb: WARN
    org.apache: WARN
    ch: WARN
  file: ./app.log

management:
  server:
    add-application-context-header: false
  endpoint:
    metrics:
      enabled: false